rem_csf_connector_client_client_node_id: "node-1"
rem_csf_connector_client_client_jks_file: "csf-client.jks"
rem_csf_connector_client_client_jks_pass: "cisco123"
rem_csf_connector_client_client_in_topic: "d-conn-c-in-node-0"
rem_csf_connector_client_client_out_topic: "d-conn-c-out-node-0"
rem_csf_connector_client_client_file_in_topic: "f-conn-c-in-node-0"
rem_csf_connector_client_websock_server_ip: "localhost"
rem_csf_connector_client_websock_server_port: "8443"
rem_csf_connector_client_metrics_delay_seconds: "30"
rem_csf_connector_client_client_file_storage_location: "/tmp/csf.connector.file.storage/"
rem_csf_connector_client_client_kafka_group_id: "c-conn-consumer-group-node-1"
rem_csf_connector_client_bootstrap_servers: "csf-dev-010:9092"
rem_csf_connector_client_log4j_rollingFileAppender_filelocation: "/tmp"
rem_csf_connector_client_log4j_rollingFileAppender_fileNamePrefix: "client"
