---
#
# aasf-infra-auto/roles/central-deploy/tasks/aasf-health.yml
#

- name: create logging stub files for Node0 aasf-health subcomponents
  file:
    path="/var/log/{{ component }}/{{ subcomponent }}.log"
    owner={{ component }}
    group={{ cen_user_grp }}
    mode=0664
    state=touch
  with_items:
    - "main"
    - "main-err"
  loop_control:
    loop_var: subcomponent

- name: put sysconfig and service files into place for Node0 aasf-health subcomponents
  template:
    src="{{ component }}-{{ subcomponent.name }}.{{ subcomponent.type }}.j2"
    dest="{{ subcomponent.target }}/{{ component }}-{{ subcomponent.name }}.{{ subcomponent.type }}"
    owner=root
    group=root
    mode=0644
    backup=no
  with_items:
    - { name: 'main', type: 'sysconfig', target: '/etc/sysconfig' }
    - { name: 'main', type: 'service', target: '/lib/systemd/system' }
  loop_control:
    loop_var: subcomponent

- name: enable Node0 aasf-health subcomponent services
  service:
    enabled=yes
    state=restarted
    name="{{ component }}-{{ subcomponent }}"
  with_items:
    - main
  loop_control:
    loop_var: subcomponent
