rem_csf_connector_server_server_node_id: "node-0"
rem_csf_connector_server_metrics_delay_seconds: "30"
rem_csf_connector_server_server_jks_file: "csf-server.jks"
rem_csf_connector_server_server_jks_pass: "cisco123"
rem_csf_connector_server_jetty_https_port: "8443"
rem_csf_connector_server_jetty_http_port: "8080"
rem_csf_connector_server_jetty_http_ip: ""
rem_csf_connector_server_server_out_topic_prefix: "d-conn-s-out-"
rem_csf_connector_server_server_in_topic_prefix: "d-conn-s-in-"
rem_csf_connector_server_server_file_in_topic_prefix: "f-conn-s-in-"
rem_csf_connector_server_server_file_storage_location: "/tmp/csf.connector.file.storage/"
rem_csf_connector_server_server_kafka_group_id: "s-conn-consumer-group"
rem_csf_connector_server_rdbms_url: "jdbc:postgresql://localhost:5432/csf_database"
rem_csf_connector_server_rdbms_username: "csfuser"
rem_csf_connector_server_rdbms_password: ""
rem_csf_connector_server_rdbms_driver: "org.postgresql.Driver"
rem_csf_connector_server_rdbms_validation_query: "SELECT 1"
rem_csf_connector_server_log4j_rollingFileAppender_filelocation: "/tmp"
rem_csf_connector_server_log4j_rollingFileAppender_fileNamePrefix: "server"
