rem_csf_health_csf_healthmanager_isremote: "0"
rem_csf_health_rdbms_url: "jdbc:postgresql\://csf-dev-010:5432/csf_database_latest?"
rem_csf_health_rdbms_username: "csfuser"
rem_csf_health_rdbms_password: ""
rem_csf_health_rdbms_driver: "org.postgresql.Driver"
rem_csf_health_bootstrap_servers: "csf-dev-005.cisco.com:9092,csf-dev-006.cisco.com:9092,csf-dev-007.cisco.com:9092"
rem_csf_health_acks: "all"
rem_csf_health_retries: "0"
rem_csf_health_batch_size: "16384"
rem_csf_health_linger_ms: "1"
rem_csf_health_buffer_memory: "33554432"
rem_csf_health_key_serializer: "org.apache.kafka.common.serialization.ByteArraySerializer"
rem_csf_health_value_serializer: "org.apache.kafka.common.serialization.ByteArraySerializer"
rem_csf_health_enable_auto_commit: "false"
rem_csf_health_auto_commit_interval_ms: "1000"
rem_csf_health_session_timeout_ms: "30000"
rem_csf_health_key_deserializer: "org.apache.kafka.common.serialization.ByteArrayDeserializer"
rem_csf_health_value_deserializer: "org.apache.kafka.common.serialization.ByteArrayDeserializer"
rem_csf_health_csf_log_dir: "/tmp/logs"
rem_csf_health_csf_event_batch_file_topic: "bf_conn_in_00000000-0000-0000-0000-000000000000"
rem_csf_health_csf_event_bootstrap_servers: "csf-dev-008.cisco.com:9092"
rem_csf_health_csf_event_consumer_group_id: "csf-event-consumer"
rem_csf_health_csf_event_consumer_topic: "csf-events"
rem_csf_health_csf_event_cotrol_command_group_id: "csf-event-control-command"
rem_csf_health_csf_event_control_command_topic: "control-topic-out"
rem_csf_health_csf_event_consumer_out_group_id: "csf-event-consumer_out"
rem_csf_health_csf_event_consumer_out_topic: "bd_conn_in_00000000-0000-0000-0000-000000000000"
rem_csf_health_cws_uri_base: "https://csf-dev-010.cisco.com:7443/api/v1"
rem_csf_health_csf_diagnostictrace_consumer_group_id: "csf-diagnostictrace-consumer"
rem_csf_health_csf_diagnostictrace_topic: "trace-control-topic"
